name: backend
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy .env.example
        run: cp .env.example .env
      
      - name: run docker compose
        run: docker compose up -d --build
      - run: docker compose exec php composer update

      - name: init laravel 
        run: |
          docker compose exec php php artisan jwt:secret
          docker compose exec php php artisan laravel:start

      - name: migrate db
        run: docker compose exec php php artisan migrate:refresh --seed

      - name: run php test 
        run: docker compose exec php php artisan test
      
      
      

        